export const CONNECTION = 'connection';
export const DISCONNECT = 'disconnect';
export const FULL = 'full';
export const HOST = 'host';
export const GUEST = 'guest';
export const LEAVE = 'leave';
export const OTHERDISC = 'other disconnected';
export const ENOUGH = 'enough players';
export const CANSTART = 'can start';
export const UP = 'up';
export const DOWN = 'down';
export const OTHERLAUNCH = 'other launch';
export const STOPMOVING = 'stop moving';
export const START = 'start';
export const STOP = 'stop';
export const SYNCBALL = 'sync ball'
export const STARTOTHER = 'start other';
export const SYNCSCORES = 'sync scores'
